import domainclasses.Event
import domainclasses.Participant
import java.sql.Statement

class JdbcParticipantRepository : ParticipantRepository {

    // Save participant to db,
    override fun save(participant: Participant): Participant {
        return if (participant.id == null) {
            insert(participant)
        } else {
            update(participant)
        }
    }

    private fun insert(participant: Participant): Participant {
        val sql = "INSERT INTO participants (name) VALUES (?)"

        Database.getConnection().use { conn ->
            conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS).use { ps ->
                ps.setString(1, participant.name)
                ps.executeUpdate()

                ps.generatedKeys.use { rs ->
                    if (rs.next()) {
                        val newId = rs.getLong(1) // get the autogenerated id
                        return Participant(name = participant.name, id = newId) // Create new participant
                    } else {
                        error("No ID returned from INSERT")
                    }
                }
            }
        }
    }

    private fun update(participant: Participant): Participant {
        val sql = "UPDATE participants SET name = ? WHERE id = ?"

        Database.getConnection().use { conn ->
            conn.prepareStatement(sql).use { ps ->
                ps.setString(1, participant.name) // Set name parameter
                ps.setLong(2, participant.id!!) // Add the non-null existing ID
                ps.executeUpdate()
            }
        }
        return participant // Return the updated participant object
    }

    override fun findById(id: Long): Participant? {
        val sql = "SELECT id, name FROM participants WHERE id = ?"

        Database.getConnection().use { conn ->
            conn.prepareStatement(sql).use { ps ->
                ps.setLong(1, id)
                ps.executeQuery().use { rs ->
                    return if (rs.next()) {
                        Participant(
                            name = rs.getString("name"),
                            id = rs.getLong("id")
                        )
                    } else {
                        null // No participant found with the given ID
                    }
                }
            }
        }
    }

    override fun findAll(): List<Participant> {
        val sql = "SELECT id, name FROM participants"
        val result = mutableListOf<Participant>() // list of participant objects

        Database.getConnection().use { conn ->
            conn.createStatement().use { stmt ->
                stmt.executeQuery(sql).use { rs ->
                    while (rs.next()) {
                        result.add(
                            Participant(
                                name = rs.getString("name"),
                                id = rs.getLong("id")
                            )
                        )
                    }
                }
            }
        }
        return result
    }
}